### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by jDolba**
allowing PHP 8 in composer requirements with PHP8 on Travis as well

### CODE REVIEW

**Comment by jDolba** [comment]
not quite sure what is wrong in CI:  tried locally with both failing PHP versions (7.2 , 7.3) and I am not able to reproduce error in travis 🤔

**Comment by sserbin** [comment]
thanks @jDolba ! 
> not quite sure what is wrong in CI

seems like symfony polyfill-mbstring is using 7.4 syntax (even though they're 7.1+ compatible). I'll get a pr open for that.

I'm fine with bumping php requirements to `^7.4|^8.0` though :+1:

**Comment by sserbin** [comment]
> seems like symfony polyfill-mbstring is using 7.4 syntax (even though they're 7.1+ compatible). I'll get a pr open for that.

https://github.com/symfony/polyfill/pull/361

**Comment by sserbin** [comment]
@jDolba can you rebase this branch on master (or merge in master) (I don't seem to have write permissions to your fork)

**Comment by sserbin** [comment]
> but no CI check was triggered thinking

yeah and I can't trigger it manually in travis :shrug: nvm though this should be good

> do you still want me to bump PHP versions ?

I'll bump it separately after releasing this pr

**Review by sserbin — APPROVED** [review]

**Comment by sserbin** [comment]
Released this as 2.2.0.
Dropped support for <7.4 php in release 3.0.0

Thanks for contributing @jDolba :+1: !

**Pull request merged**
